aplayer: aplayer.cpp stdafx.cpp
	g++ -o aplayer aplayer.cpp stdafx.cpp -I. -lao -lavcodec -lavformat

aplayer.osx: aplayer.cpp stdafx.cpp
	g++ -o aplayer aplayer.cpp stdafx.cpp -I. -lao -lavcodec -lavformat -lavutil -lz -lbz2 -framework CoreFoundation -framework CoreVideo -framework VideoDecodeAcceleration
